apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-features
data:
    failToDefault: {{ .Values.features.failToDefault }}
    configProvider: {{ .Values.features.configProvider }}
    apiKeyExpDays: {{ .Values.features.apiKeyExpDays }}
---
{{- if eq .Values.features.configProvider "" -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-appsettings
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }
{{- end }}