apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-features
data:
    failToDefault: {{ .Values.features.failToDefault }}
    configProvider: {{ .Values.features.configProvider }}
    apiKeyExpDays: {{ .Values.features.apiKeyExpDays }}
---
{{- if eq .Values.features.configProvider "appsettings" -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-appsettings
data:
  appsettings.json: |-
    {{ .Files.Get .Values.appSettingsPath | indent 2 }}
{{- end }}