apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.docker.configjson }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dockercred
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson