apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secrets
data:
    {{- if eq .Values.features.configProvider "azure" }}
    azAppConfigConnStr: {{ .Values.env.azAppConfigConnStr | b64enc }}
    azAppConfigLabelFilter: {{ .Values.env.azAppConfigLabelFilter | b64enc }}
    {{- end }}