apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secrets
data:
    azAppConfigConnStr: {{ .Values.env.azAppConfigConnStr | b64enc }}
    azAppConfigLabelFilter: {{ .Values.env.azAppConfigLabelFilter | b64enc }}